site_name: Amine RACHYD

theme:
  name: material
  palette:
    scheme: slate
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky # Tabs sticking even if scrolling
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - navigation.top
    - navigation.footer
    # Table of content
    - toc.follow
    # Code blocks
    - content.code.copy
    - content.code.select
    # Search
    - search.suggest

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aminerachyd
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/RachydAmine
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amine-rachyd/
    - icon: fontawesome/solid/paper-plane
      link: mailto:aminerachyd99@gmail.com

plugins:
  - offline
  - search
  - awesome-pages

repo_url: https://github.com/aminerachyd/website
repo_name: aminerachyd/website

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
