site_name: Amine RACHYD

theme:
  name: material
  palette:
    scheme: slate
    toggle:
      icon: material/brightness-7 
      name: Switch to dark mode
    primary: black
    accent: indigo
  font:
    text: Roboto
    code: JetBrains Mono
  features:
    - navigation.instant
    - navigation.instant.preview
    - navigation.tracking
    - navigation.tabs
    - navigation.tabs.sticky # Tabs sticking even if scrolling
    - navigation.sections
    - navigation.expand
    - navigation.path
    - navigation.indexes
    - toc.follow
    - navigation.top
    - navigation.footer

extra:
  generator: false
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/aminerachyd
    - icon: fontawesome/brands/x-twitter
      link: https://twitter.com/RachydAmine
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/amine-rachyd/
    - icon: fontawesome/solid/paper-plane
      link: mailto:aminerachyd99@gmail.com

plugins:
  - offline
  - search
  - awesome-pages
